Controllers/BenhVienController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Data;
using Microsoft.AspNetCore.Mvc.Rendering;
using QuanLyVienPhi.Models;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;

namespace QuanLyVienPhi.Controllers
{
    public class BenhVienController : Controller
    {
        DAL.DS ds = new DAL.DS();
        DAL.InsertData inData = new DAL.InsertData();
        DAL.GetInfo getI = new DAL.GetInfo();
        DAL.UpdateData upData = new DAL.UpdateData();
        DAL.DeleteData delData = new DAL.DeleteData();

        //--------------------BACSI---------------------------
        public IActionResult BacSi(int page = 1)
        {
            // khai báo và lấy thông tin từ sesstion
            var ts = JsonConvert.DeserializeObject<Account>(HttpContext.Session.GetString("session"));
            ViewBag.Session = ts._sMaLoai.ToLower().Trim();
            if (ViewBag.Session == "AD".Trim().ToLower() || ViewBag.Session == "KT".ToLower())
            {
                IList<Physician> listPhy = (List<Physician>)getI.GetAllPhysician();
                const int pageSize = 5;// danh sach hien thi
                if (page < 1)
                    page = 1;
                int recsCount = listPhy.Count;
                var pager = new PageList(recsCount, page, pageSize);
                int recSkip = (page - 1) * pageSize;
                var listData = listPhy.Skip(recSkip).Take(pager.PageSize).ToList();
                this.ViewBag.Pager = pager;
                return View(listData);
            }
            else
            {
                return NotFound();
            }

        }
        public ActionResult ThemBacSi()
        {
            // khai báo và lấy thông tin từ sesstion
            var ts = JsonConvert.DeserializeObject<Account>(HttpContext.Session.GetString("session"));
            ViewBag.Session = ts._sMaLoai.ToLower().Trim();
            if (ViewBag.Session == "AD".Trim().ToLower() || ViewBag.Session == "KT".ToLower())
            {
                DataSet department = ds.GetDepartment();
                List<SelectListItem> listDepartment = new List<SelectListItem>();
                foreach (DataRow dr in department.Tables[0].Rows)
                {
                    listDepartment.Add(new SelectListItem { Text = dr["TenPhongKham"].ToString().Trim(), Value = dr["MAPK"].ToString() });
                }
                ViewBag.InfoDepartment = listDepartment;

                DataSet faculty = ds.GetFaculty();
                List<SelectListItem> listFaculty = new List<SelectListItem>();
                foreach (DataRow dr in faculty.Tables[0].Rows)
                {
                    listFaculty.Add(new SelectListItem { Text = dr["TenKhoa"].ToString().Trim(), Value = dr["MaKhoa"].ToString().Trim() });
                }
                ViewBag.InfoFaculty = listFaculty;
                return View();
            }
            else
            {
                return NotFound();
            }

        }

        [HttpPost]
        public ActionResult ThemBacSi([Bind] Physician phy)
        {
            try
            {
                DataSet department = ds.GetDepartment();
                List<SelectListItem> listDepartment = new List<SelectListItem>();
                foreach (DataRow dr in department.Tables[0].Rows)
                {
                    listDepartment.Add(new SelectListItem { Text = dr["TenPhongKham"].ToString().Trim(), Value = dr["MAPK"].ToString() });
                }
                ViewBag.InfoDepartment = listDepartment;

                DataSet faculty = ds.GetFaculty();
                List<SelectListItem> listFaculty = new List<SelectListItem>();
                foreach (DataRow dr in faculty.Tables[0].Rows)
                {
                    listFaculty.Add(new SelectListItem { Text = dr["TenKhoa"].ToString().Trim(), Value = dr["MaKhoa"].ToString().Trim() });
                }
                ViewBag.InfoFaculty = listFaculty;

                if (ModelState.IsValid)
                {
                    inData.InsertPhysician(phy);
                    return RedirectToAction("BacSi");
                }
            }
            catch (Exception e)
            {
                TempData["mgs"] = e.Message.ToString();
            }
            return View();
        }

        public ActionResult SuaBacSi(string id)
        {
            // khai báo và lấy thông tin từ sesstion
            var ts = JsonConvert.DeserializeObject<Account>(HttpContext.Session.GetString("session"));
            ViewBag.Session = ts._sMaLoai.ToLower().Trim();
            if (ViewBag.Session == "AD".Trim().ToLower() || ViewBag.Session == "KT".ToLower())
            {
                if (id == null) return NotFound();
                Physician physician = getI.GetPhysicianByID(id);
                return View(physician);
            }
            else
            {
                return NotFound();
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SuaBacSi(string id, [Bind] Physician phy)
        {
            try
            {
                if (id == null) return NotFound();
                if (ModelState.IsValid)
                {
                    upData.UpdatePhysician(id, phy);
                    return RedirectToAction("BacSi");
                }
            }
            catch (Exception)
            {
                return NotFound();
            }
            return View(upData);
        }

        public ActionResult ChiTietBacSi(string id)
        {
            // khai báo và lấy thông tin từ sesstion
            var ts = JsonConvert.DeserializeObject<Account>(HttpContext.Session.GetString("session"));
            ViewBag.Session = ts._sMaLoai.ToLower().Trim();
            if (ViewBag.Session == "AD".Trim().ToLower() || ViewBag.Session == "KT".ToLower())
            {
                if (id == null) return NotFound();
                VPhysician physician = getI.GetVPhysicianByID(id);
                return View(physician);
            }
            else
            {
                return NotFound();
            }

        }

        public ActionResult XoaBacSi(string id)
        {
            // khai báo và lấy thông tin từ sesstion
            var ts = JsonConvert.DeserializeObject<Account>(HttpContext.Session.GetString("session"));
            ViewBag.Session = ts._sMaLoai.ToLower().Trim();
            if (ViewBag.Session == "AD".Trim().ToLower() || ViewBag.Session == "KT".ToLower())
            {
                if (id == null) return NotFound();
                VPhysician physician = getI.GetVPhysicianByID(id);
                return View(physician);
            }
            else
            {
                return NotFound();
            }

        }

        public ActionResult XacNhan(string id)
        {
            if (id != null)
                delData.DeletePhysician(id);
            return RedirectToAction("BacSi");
        }
        //-------------------NHANVIEN--------------------
        public ActionResult NhanVien(int page = 1)
        {
            // khai báo và lấy thông tin từ sesstion
            var ts = JsonConvert.DeserializeObject<Account>(HttpContext.Session.GetString("session"));
            ViewBag.Session = ts._sMaLoai.ToLower().Trim();
            if (ViewBag.Session == "AD".Trim().ToLower() || ViewBag.Session == "KT".ToLower())
            {
                IList<Employee> listEmp = (List<Employee>)getI.GetAllEmployee();
                const int pageSize = 5;// danh sach hien thi
                if (page < 1)
                    page = 1;
                int recsCount = listEmp.Count;
                var pager = new PageList(recsCount, page, pageSize);
                int recSkip = (page - 1) * pageSize;
                var listData = listEmp.Skip(recSkip).Take(pager.PageSize).ToList();
                this.ViewBag.Pager = pager;
                return View(listData);
            }
            else
            {
                return NotFound();
            }

        }
        public ActionResult ThemNhanVien()
        {
            // khai báo và lấy thông tin từ sesstion
            var ts = JsonConvert.DeserializeObject<Account>(HttpContext.Session.GetString("session"));
            ViewBag.Session = ts._sMaLoai.ToLower().Trim();
            if (ViewBag.Session == "AD".Trim().ToLower() || ViewBag.Session == "KT".ToLower())
            {
                return View();
            }
            else
            {
                return NotFound();
            }

        }

        [HttpPost]
        public ActionResult ThemNhanVien([Bind] Employee ee)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    inData.InsertEmployee(ee);
                    return RedirectToAction("NhanVien");
                }
            }
            catch (Exception e)
            {
                TempData["mgs"] = e.Message.ToString();
            }
            return View();
        }

        public ActionResult SuaNhanVien(string id)
        {
            // khai báo và lấy thông tin từ sesstion
            var ts = JsonConvert.DeserializeObject<Account>(HttpContext.Session.GetString("session"));
            ViewBag.Session = ts._sMaLoai.ToLower().Trim();
            if (ViewBag.Session == "AD".Trim().ToLower() || ViewBag.Session == "KT".ToLower())
            {
                if (id == null) return NotFound();
                Employee emp = getI.GetEmployeeByID(id);
                return View(emp);
            }
            else
            {
                return NotFound();
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SuaNhanVien(string id, [Bind] Employee ee)
        {
            try
            {
                if (id == null) return NotFound();

Views/BenhVien/BacSi.cshtml
@model IEnumerable<QuanLyVienPhi.Models.Physician>;
@{
    ViewData["Title"] = "Bác sĩ";
    if (ViewBag.Session == "Ad".ToLower().Trim())
    {
        Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    }
    else if (ViewBag.Session == "KT".ToLower().Trim())
    {
        Layout = "~/Views/Shared/_LayoutKeToan.cshtml";
    }
    PageList pager = new PageList();
    int pageNo = 0;
    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }
}

<!-- [ breadcrumb ] start -->
<div class="page-header">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-12">
                <div class="page-header-title">

                </div>
                <ul class="breadcrumb">
                    @*<li class="breadcrumb-item"><a href="#"><i class="feather icon-home"></i></a></li>*@
                    <li class="breadcrumb-item"><a href="@Url.Action("BacSi")">Bệnh viện</a></li>
                    <li class="breadcrumb-item"><a href="@Url.Action("BacSi")">Bác sĩ</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- [ table ] start -->
<div class="col-xl-12">
    <div class="card">
        <div class="card-header">
            <h5>Bác sĩ</h5>
        </div>
        <div class="card-block table-border-style">
            <div class="row">
                <div class="col-md-6">
                    <!--Tim kiem---------------------------------------------------------------------------------------------------------------------------->
                    <div class="input-group mb-3">
                        <input type="search" id="Search" class="form-control" placeholder="Tìm kiếm...">
                        <div class="input-group-append">
                            <button class="btn btn-success feather icon-search" type="button">    Tìm</button>
                        </div>
                    </div>
                </div>
                <div class="col-md-6" style="text-align: right; padding-top: 10px">
                    <a asp-controller="BenhVien" asp-action="ThemBacSi" class="btn btn-primary feather icon-plus" style="text-align:right;">     Thêm</a>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table table-striped content-table colortoptableone">
                    <thead>
                        <tr>
                            <th>Mã bác sĩ</th>
                            <th>Tên bác sĩ</th>
                            <th>Ngày sinh</th>
                            <th>Giới tính</th>
                            <th>Điện thoại</th>
                            <th>Email</th>
                            <th>Chức năng</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr class="Search">
                                <td>@Html.DisplayFor(m => item._sMaBS)</td>
                                <td>@Html.DisplayFor(m => item._sHoTen)</td>
                                <td>@String.Format("{0:dd/MM/yyyy}", item._dNgaySinh)</td>
                                <td>@Html.DisplayFor(m => item._sGioiTinh)</td>
                                <td>@Html.DisplayFor(m => item._sSDT)</td>
                                <td>@Html.DisplayFor(m => item._sEmail)</td>
                                <td>
                                    <a href="@Url.Action("ChiTietBacSi", "BenhVien", new { id = item._sMaBS})" class="btn btn-info feather icon-file-text"></a>
                                    <a href="@Url.Action("SuaBacSi", "BenhVien", new { id = item._sMaBS})" class="btn btn-success feather icon-edit"></a>
                                    <a href="@Url.Action("XoaBacSi", "BenhVien", new { id = item._sMaBS})" class="btn btn-danger feather icon-trash-2"></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                <!--Phan trang-->
                <nav aria-label="Page navigation example">
                    @if (pager.TotalPages > 0)
                    {
                        <ul class="pagination">
                            @if (pager.CurrentPage > 1)
                            {
                                <li class="page-item">
                                    <a class="page-link" href="@Url.Action( "BacSi", "BenhVien", new {page =1})">Frist</a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link" href="@Url.Action( "BacSi","BenhVien", new {page =pager.CurrentPage - 1})">Previous</a>
                                </li>
                            }

                            @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
                            {
                                <li class="page-item @(pge == pager.CurrentPage ? "active":"")">
                                    <a class="page-link" href="@Url.Action("BacSi", "BenhVien", new { page = @pge})">@pge</a>
                                </li>

                            }

                            @if (pager.CurrentPage < pager.TotalPages)
                            {
                                <li class="page-item">
                                    <a class="page-link" href="@Url.Action( "BacSi","BenhVien", new {page = pager.CurrentPage + 1 })">Next</a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link" href="@Url.Action("BacSi", "BenhVien", new {page = pager.TotalPages })">Last</a>
                                </li>
                            }
                        </ul>
                    }
                </nav>
            </div>
        </div>
    </div>
</div>
<!-- [ table ] end -->

Views/BenhVien/ChiTietBacSi.cshtml
@model QuanLyVienPhi.Models.VPhysician

@{
    ViewData["Title"] = "ChiTietBacSi";
    if (ViewBag.Session == "Ad".ToLower().Trim())
    {
        Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    }
    else if (ViewBag.Session == "KT".ToLower().Trim())
    {
        Layout = "~/Views/Shared/_LayoutKeToan.cshtml";
    }
}

<div class="page-header">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-12">
                <div class="page-header-title">

                </div>
                <ul class="breadcrumb">
                    @*<li class="breadcrumb-item"><a href="#"><i class="feather icon-home"></i></a></li>*@
                    <li class="breadcrumb-item"><a href="@Url.Action("BacSi")">Bác sĩ</a></li>
                    <li class="breadcrumb-item"><a href="@Url.Action("ChiTietBacSi")">Thông tin bác sĩ</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="col-sm-12">
    <div class="card">
        <div class="card-header">
            <h5>Thông tin bác sĩ</h5>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-12">
                    <dl class="row">
                        <dt class="col-sm-2">Mã bác sĩ</dt>
                        <dd class="col-sm-10">
                            : @Html.DisplayFor(model => model._sMaBS)
                        </dd>
                        <dt class="col-sm-2">Họ tên</dt>
                        <dd class="col-sm-10">
                            : @Html.DisplayFor(model => model._sHoTen)
                        </dd>
                        <dt class="col-sm-2">Ngày sinh</dt>
                        <dd class="col-sm-10">
                            : @String.Format("{0:dd/MM/yyyy}", Model._dNgaySinh)
                        </dd>
                        <dt class="col-sm-2">Địa chỉ</dt>
                        <dd class="col-sm-10">
                            : @Html.DisplayFor(model => model._sDiaChi)
                        </dd>
                        <dt class="col-sm-2">Giới tính</dt>
                        <dd class="col-sm-10">
                            : @Html.DisplayFor(model => model._sGioiTinh)
                        </dd>
                        <dt class="col-sm-2">Điện thoại</dt>
                        <dd class="col-sm-10">
                            : @Html.DisplayFor(model => model._sSDT)
                        </dd>
                        <dt class="col-sm-2">Email</dt>
                        <dd class="col-sm-10">
                            : @Html.DisplayFor(model => model._sEmail)
                        </dd>
                        <dt class="col-sm-2">Tên phòng khám</dt>
                        <dd class="col-sm-10">
                            : @Html.DisplayFor(model => model._sTenPK)
                        </dd>
                        <dt class="col-sm-2">Tên khoa</dt>
                        <dd class="col-sm-10">
                            : @Html.DisplayFor(model => model._sTenKhoa)
                        </dd>
                    </dl>
                    <a asp-controller="BenhVien" asp-action="BacSi"
                       class="btn btn-outline-secondary feather icon-corner-down-right">     Trở về</a>
                </div>
            </div>
        </div>
    </div>
</div>

Views/BenhVien/Khoa.cshtml
@model IEnumerable<QuanLyVienPhi.Models.Faculty>;
@{
    ViewData["Title"] = "Khoa";
    if (ViewBag.Session == "Ad".ToLower().Trim())
    {
        Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    }
    else if (ViewBag.Session == "KT".ToLower().Trim())
    {
        Layout = "~/Views/Shared/_LayoutKeToan.cshtml";
    }
    PageList pager = new PageList();
    int pageNo = 0;
    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }
}

<div class="page-header">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-12">
                <div class="page-header-title">

                </div>
                <ul class="breadcrumb">
                   @* <li class="breadcrumb-item"><a href="#"><i class="feather icon-home"></i></a></li>*@
                    <li class="breadcrumb-item"><a href="@Url.Action("Khoa")">Bệnh viện</a></li>
                    <li class="breadcrumb-item"><a href="@Url.Action("Khoa")">Khoa</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<!-- [ table ] start -->
<div class="col-xl-12">
    <div class="card">
        <div class="card-header">
            <h5>Khoa</h5>
        </div>
        <div class="card-block table-border-style">
            <div style="text-align:right;">
                <a asp-controller="BenhVien" asp-action="ThemKhoa" class="btn btn-primary feather icon-plus" style="text-align:right;">     Thêm</a>
            </div>
            <div class="table-responsive">
                <table class="table table-striped content-table colortoptable">
                    <thead>
                        <tr>
                            <th>Mã khoa</th>
                            <th>Tên khoa</th>
                            <th>Số bác sĩ</th>
                            <th>Chức năng</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@Html.DisplayFor(m => item._sMaKhoa)</td>
                                <td>@Html.DisplayFor(m => item._sTenKhoa)</td>
                                <td>@Html.DisplayFor(m => item._nSoLuong)</td>
                                <td>
                                    <a href="@Url.Action("SuaKhoa", "BenhVien", new { id = item._sMaKhoa })"
                                       class="btn btn-success feather icon-edit"></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                <!--Phan trang-->
                <nav aria-label="Page navigation example">
                    @if (pager.TotalPages > 0)
                    {
                        <ul class="pagination">
                            @if (pager.CurrentPage > 1)
                            {
                                <li class="page-item">
                                    <a class="page-link" href="@Url.Action("Khoa", "BenhVien", new {page =1})">Frist</a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link" href="@Url.Action("Khoa", "BenhVien", new {page =pager.CurrentPage - 1})">Previous</a>
                                </li>
                            }

                            @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
                            {
                                <li class="page-item @(pge == pager.CurrentPage ? "active":"")">
                                    <a class="page-link" href="@Url.Action("Khoa", "BenhVien", new { page = @pge})">@pge</a>
                                </li>

                            }

                            @if (pager.CurrentPage < pager.TotalPages)
                            {
                                <li class="page-item">
                                    <a class="page-link" href="@Url.Action("Khoa", "BenhVien", new {page = pager.CurrentPage + 1 })">Next</a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link" href="@Url.Action( "Khoa","BenhVien", new {page = pager.TotalPages })">Last</a>
                                </li>
                            }
                        </ul>
                    }
                </nav>
            </div>
        </div>
    </div>
</div>
<!-- [ table ] end -->

Views/BenhVien/NhanVien.cshtml
@model IEnumerable<QuanLyVienPhi.Models.Employee>;
@{
    ViewData["Title"] = "Nhân viên";
    if (ViewBag.Session == "Ad".ToLower().Trim())
    {
        Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    }
    else if (ViewBag.Session == "KT".ToLower().Trim())
    {
        Layout = "~/Views/Shared/_LayoutKeToan.cshtml";
    }
    PageList pager = new PageList();
    int pageNo = 0;
    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }
}

<div class="page-header">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-12">
                <div class="page-header-title">

                </div>
                <ul class="breadcrumb">
                    @*<li class="breadcrumb-item"><a href="#"><i class="feather icon-home"></i></a></li>*@
                    <li class="breadcrumb-item"><a href="@Url.Action("NhanVien")">Bệnh viện</a></li>
                    <li class="breadcrumb-item"><a href="@Url.Action("NhanVien")">Nhân viên</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<!-- [ table ] start -->
<div class="col-xl-12">
    <div class="card">
        <div class="card-header">
            <h5>Nhân viên</h5>
        </div>
        <div class="card-block table-border-style">
            <div class="row">
                <div class="col-md-6">
                    <!--Tim kiem---------------------------------------------------------------------------------------------------------------------------->
                    <div class="input-group mb-3">
                        <input type="search" id="Search" class="form-control" placeholder="Tìm kiếm...">
                        <div class="input-group-append">
                            <button class="btn btn-success feather icon-search" type="button">    Tìm</button>
                        </div>
                    </div>
                </div>
                <div class="col-md-6" style="text-align: right; padding-top: 10px">
                    <a asp-controller="BenhVien" asp-action="ThemNhanVien" class="btn btn-primary feather icon-plus" style="text-align:right;">     Thêm</a>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table table-striped content-table colortoptableone">
                    <thead>
                        <tr>
                            <th>Mã nhân viên</th>
                            <th>Tên nhân viên</th>
                            <th>Ngày sinh</th>
                            <th>Giới tính</th>
                            <th>Điện thoại</th>
                            <th>Email</th>
                            <th>Địa chỉ</th>
                            <th>Chức năng</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr class="Search">
                                <td>@Html.DisplayFor(modelItem => item._sMaNV)</td>
                                <td>@Html.DisplayFor(modelItem => item._sHoTen)</td>
                                <td>@String.Format("{0:dd/MM/yyyy}", item._dNgaySinh)</td>
                                <td>@Html.DisplayFor(modelItem => item._sGioiTinh)</td>
                                <td>@Html.DisplayFor(modelItem => item._sSDT)</td>
                                <td>@Html.DisplayFor(modelItem => item._sEmail)</td>
                                <td>@Html.DisplayFor(modelItem => item._sDiaChi)</td>
                                <td>
                                    <a href="@Url.Action("SuaNhanVien", "BenhVien", new { id = item._sMaNV})" class="btn btn-success feather icon-edit"></a>
                                    <a href="@Url.Action("XoaNhanVien", "BenhVien", new { id = item._sMaNV})" class="btn btn-danger feather icon-trash-2"></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                <!--Phan trang-->
                <nav aria-label="Page navigation example">
                    @if (pager.TotalPages > 0)
                    {
                        <ul class="pagination">
                            @if (pager.CurrentPage > 1)
                            {
                                <li class="page-item">
                                    <a class="page-link" href="@Url.Action("NhanVien", "BenhVien", new {page =1})">Frist</a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link" href="@Url.Action("NhanVien", "BenhVien", new {page =pager.CurrentPage - 1})">Previous</a>
                                </li>
                            }

                            @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
                            {
                                <li class="page-item @(pge == pager.CurrentPage ? "active":"")">
                                    <a class="page-link" href="@Url.Action("NhanVien", "BenhVien", new { page = @pge})">@pge</a>
                                </li>

                            }

                            @if (pager.CurrentPage < pager.TotalPages)
                            {
                                <li class="page-item">
                                    <a class="page-link" href="@Url.Action("NhanVien", "BenhVien", new {page = pager.CurrentPage + 1 })">Next</a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link" href="@Url.Action("NhanVien", "BenhVien", new {page = pager.TotalPages })">Last</a>
                                </li>
                            }
                        </ul>
                    }
                </nav>
            </div>
        </div>
    </div>
</div>
<!-- [ table ] end -->