Controllers/TaiKhoanController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Data;
using System.Data.SqlClient;
using Microsoft.AspNetCore.Mvc.Rendering;
using QuanLyVienPhi.Models;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;

namespace QuanLyVienPhi.Controllers
{
    public class TaiKhoanController : Controller
    {
        DAL.DS ds = new DAL.DS();
        DAL.InsertData inData = new DAL.InsertData();
        DAL.GetInfo getI = new DAL.GetInfo();
        DAL.UpdateData upData = new DAL.UpdateData();

        public IActionResult LoaiTaiKhoan(int page = 1)
        {
            // khai báo và lấy thông tin từ sesstion
            var ts = JsonConvert.DeserializeObject<Account>(HttpContext.Session.GetString("session"));
            ViewBag.Session = ts._sMaLoai.ToLower().Trim();

            if (ViewBag.Session == "AD".ToLower().Trim())
            {
                IList<AccountGroup> listGroups = (List<AccountGroup>)getI.GetAllAccountGroup();
                const int pageSize = 5;// danh sach hien thi
                if (page < 1)
                    page = 1;
                int recsCount = listGroups.Count;
                var pager = new PageList(recsCount, page, pageSize);
                int recSkip = (page - 1) * pageSize;
                var listData = listGroups.Skip(recSkip).Take(pager.PageSize).ToList();
                this.ViewBag.Pager = pager;
                return View(listData);
            }
            else
            {
                return NotFound();
            }

        }
        public IActionResult ThemLoaiTaiKhoan()
        {
            // khai báo và lấy thông tin từ sesstion
            var ts = JsonConvert.DeserializeObject<Account>(HttpContext.Session.GetString("session"));
            ViewBag.Session = ts._sMaLoai.ToLower().Trim();
            if (ViewBag.Session == "AD".ToLower().Trim())
            {
                // Lát chạy thử cái này coi có lỗi ko nha
                return View();
            }
            else
            {
                return NotFound();
            }
        }

        [HttpPost]
        public IActionResult ThemLoaiTaiKhoan([Bind] AccountGroup acGr)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    inData.InsertAccountGroup(acGr);
                    return RedirectToAction("LoaiTaiKhoan");
                }
            }
            catch (Exception e)
            {
                TempData["mgs"] = e.Message.ToString();
            }
            return View();
        }

        public IActionResult SuaLoaiTaiKhoan(string id)
        {
            // khai báo và lấy thông tin từ sesstion
            var ts = JsonConvert.DeserializeObject<Account>(HttpContext.Session.GetString("session"));
            ViewBag.Session = ts._sMaLoai.ToLower().Trim();

            if (ViewBag.Session == "AD".ToLower().Trim())
            {
                if (id == null) return NotFound();
                AccountGroup aGroup = getI.GetAccountGroupByID(id);
                return View(aGroup);
            }
            else
            {
                return NotFound();
            }

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SuaLoaiTaiKhoan(string id, [Bind] AccountGroup aGroup)
        {
            try
            {
                if (id == null) return NotFound();
                if (ModelState.IsValid)
                {
                    upData.UpdateAccountGroup(id, aGroup);
                    return RedirectToAction("LoaiTaiKhoan");
                }
            }
            catch (Exception)
            {
                return NotFound();
            }
            return View(upData);
        }
        //---------------- Tài khoản nhân viên
        public IActionResult DSTaiKhoan(int page = 1)
        {
            // khai báo và lấy thông tin từ sesstion
            var ts = JsonConvert.DeserializeObject<Account>(HttpContext.Session.GetString("session"));
            ViewBag.Session = ts._sMaLoai.ToLower().Trim();

            if (ViewBag.Session == "AD".ToLower().Trim())
            {
                List<VAccount> listAcc = (List<VAccount>)getI.GetAllAccount();
                const int pageSize = 5;// danh sach hien thi
                if (page < 1)
                    page = 1;
                int recsCount = listAcc.Count;
                var pager = new PageList(recsCount, page, pageSize);
                int recSkip = (page - 1) * pageSize;
                var listData = listAcc.Skip(recSkip).Take(pager.PageSize).ToList();
                this.ViewBag.Pager = pager;
                return View(listData);
            }
            else
            {
                return NotFound();
            }

        }
        public IActionResult ThemTaiKhoan()
        {
            // khai báo và lấy thông tin từ sesstion
            var ts = JsonConvert.DeserializeObject<Account>(HttpContext.Session.GetString("session"));
            ViewBag.Session = ts._sMaLoai.ToLower().Trim();

            if (ViewBag.Session == "AD".ToLower().Trim())
            {

                DataSet accGr = ds.GetAccountGroup();
                List<SelectListItem> listAccGr = new List<SelectListItem>();
                foreach (DataRow dr in accGr.Tables[0].Rows)
                    listAccGr.Add(new SelectListItem { Text = dr["TenLoai"].ToString().Trim(), Value = dr["MaLoai"].ToString().Trim() });
                ViewBag.InfoAccGr = listAccGr;

                DataSet ee = ds.GetEmloyee();
                List<SelectListItem> listEmp = new List<SelectListItem>();
                foreach (DataRow dr in ee.Tables[0].Rows)
                    listEmp.Add(new SelectListItem { Text = dr["TenNV"].ToString().Trim(), Value = dr["MANV"].ToString().Trim() });
                ViewBag.InfoEmp = listEmp;
                return View();
            }
            else
            {
                return NotFound();
            }
        }

        [HttpPost]
        public IActionResult ThemTaiKhoan([Bind] Account acc)
        {
            try
            {
                DataSet accGr = ds.GetAccountGroup();
                List<SelectListItem> listAccGr = new List<SelectListItem>();
                foreach (DataRow dr in accGr.Tables[0].Rows)
                    listAccGr.Add(new SelectListItem { Text = dr["TenLoai"].ToString().Trim(), Value = dr["MaLoai"].ToString().Trim() });
                ViewBag.InfoAccGr = listAccGr;

                DataSet ee = ds.GetEmloyee();
                List<SelectListItem> listEmp = new List<SelectListItem>();
                foreach (DataRow dr in ee.Tables[0].Rows)
                    listEmp.Add(new SelectListItem { Text = dr["TenNV"].ToString().Trim(), Value = dr["MANV"].ToString().Trim() });
                ViewBag.InfoEmp = listEmp;

                if (ModelState.IsValid)
                {
                    inData.InsertAccount(acc);
                    return RedirectToAction("DSTaiKhoan");
                }
            }
            catch (Exception e)
            {
                TempData["mgs"] = e.Message.ToString();
            }
            return View();
        }

        public IActionResult SuaTaiKhoan(string id)
        {
            // khai báo và lấy thông tin từ sesstion
            var ts = JsonConvert.DeserializeObject<Account>(HttpContext.Session.GetString("session"));
            ViewBag.Session = ts._sMaLoai.ToLower().Trim();

            if (ViewBag.Session == "AD".ToLower().Trim())
            {
                if (id == null) return NotFound();
                Account ac = getI.GetAccountById(id);
                try
                {
                    DataSet accGr = ds.GetAccountGroup();
                    List<SelectListItem> listAccGr = new List<SelectListItem>();
                    foreach (DataRow dr in accGr.Tables[0].Rows)
                        listAccGr.Add(new SelectListItem { Text = dr["TenLoai"].ToString().Trim(), Value = dr["MaLoai"].ToString().Trim() });
                    ViewBag.InfoAccGr = listAccGr;

                    DataSet ee = ds.GetEmloyee();
                    List<SelectListItem> listEmp = new List<SelectListItem>();
                    foreach (DataRow dr in ee.Tables[0].Rows)
                        listEmp.Add(new SelectListItem { Text = dr["TenNV"].ToString().Trim(), Value = dr["MANV"].ToString().Trim() });
                    ViewBag.InfoEmp = listEmp;
                }
                catch (Exception)
                {
                    return NotFound();
                }
                return View(ac);
            }
            else
            {
                return NotFound();
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SuaTaiKhoan(string id, [Bind] Account acc)
        {
            try
            {
                if (id == null) return NotFound();

                if (ModelState.IsValid)
                {
                    upData.UpdateAccount(id, acc);
                    return RedirectToAction("DSTaiKhoan");
                }
                return View(upData);
            }
            catch (Exception e)
            {
                TempData["mgs"] = e.Message.ToString();
            }
            return View();
        }
    }
}

Views/TaiKhoan/DSTaiKhoan.cshtml
@model IEnumerable<QuanLyVienPhi.Models.VAccount>
@{
    ViewData["Title"] = "Danh sách tài khoản";
    if (ViewBag.Session == "Ad".ToLower().Trim())
    {
        Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    }
    PageList pager = new PageList();
    int pageNo = 0;
    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }
}

<div class="page-header">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-12">
                <div class="page-header-title">

                </div>
                <ul class="breadcrumb">
                    @*<li class="breadcrumb-item"><a href="@Url.Action("KeToan")"><i class="feather icon-home"></i></a></li>*@
                    <li class="breadcrumb-item"><a href="@Url.Action("DSTaiKhoan")">Tài khoản</a></li>
                    <li class="breadcrumb-item"><a href="@Url.Action("DSTaiKhoan")">Danh Sách tài khoản</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<!-- [ table ] start -->
<div class="col-xl-12">
    <div class="card">
        <div class="card-header">
            <h5>Danh sách tài khoản</h5>
        </div>
        <div class="card-block table-border-style">
            <div style="text-align:right;">
                <a asp-controller="TaiKhoan" asp-action="ThemTaiKhoan" class="btn btn-primary feather icon-plus" style="text-align:right;">     Thêm</a>
            </div>
            <div class="table-responsive">
                <table class="table table-striped content-table colortoptableone">
                    <thead>
                        <tr>
                            <th>Tên đăng nhập</th>
                            <th>Mật khẩu</th>
                            <th>Mã nhân viên</th>
                            <th>Tên nhân viên</th>
                            <th>Quyền đăng nhập</th>
                            <th>Chức năng</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item._sTaiKhoan)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item._sMatKhau)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item._sMANV)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item._sHoTen)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item._sTenLoai)
                                </td>
                                <td>
                                    <a href="@Url.Action("SuaTaiKhoan", "TaiKhoan", new { id= item._sTaiKhoan})" class="btn btn-success feather icon-edit"></a>
                                </td>
                            </tr>
                        }


                    </tbody>
                </table>
                <!--Phan trang-->
                <nav aria-label="Page navigation example">
                    @if (pager.TotalPages > 0)
                    {
                        <ul class="pagination">
                            @if (pager.CurrentPage > 1)
                            {
                                <li class="page-item">
                                    <a class="page-link" href="@Url.Action("TaiKhoan", "DSTaiKhoan", new {page =1})">Frist</a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link" href="@Url.Action("TaiKhoan", "DSTaiKhoan", new {page =pager.CurrentPage - 1})">Previous</a>
                                </li>
                            }

                            @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
                            {
                                <li class="page-item @(pge == pager.CurrentPage ? "active":"")">
                                    <a class="page-link" href="@Url.Action("TaiKhoan", "DSTaiKhoan", new { page = @pge})">@pge</a>
                                </li>

                            }

                            @if (pager.CurrentPage < pager.TotalPages)
                            {
                                <li class="page-item">
                                    <a class="page-link" href="@Url.Action("TaiKhoan", "DSTaiKhoan", new {page = pager.CurrentPage + 1 })">Next</a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link" href="@Url.Action("TaiKhoan", "DSTaiKhoan", new {page = pager.TotalPages })">Last</a>
                                </li>
                            }
                        </ul>
                    }
                </nav>
            </div>
        </div>
    </div>
</div>
<!-- [ table ] end -->

Views/TaiKhoan/LoaiTaiKhoan.cshtml
@model IEnumerable<QuanLyVienPhi.Models.AccountGroup>;
@{
    ViewData["Title"] = "Loại tài khoản";
    if (ViewBag.Session == "Ad".ToLower().Trim())
    {
        Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    }
    PageList pager = new PageList();
    int pageNo = 0;
    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }
}


<div class="page-header">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-12">
                <div class="page-header-title">

                </div>
                <ul class="breadcrumb">
                    @*<li class="breadcrumb-item"><a href="@Url.Action("KeToan")"><i class="feather icon-home"></i></a></li>*@
                    <li class="breadcrumb-item"><a href="@Url.Action("LoaiTaiKhoan")">Tài khoản</a></li>
                    <li class="breadcrumb-item"><a href="@Url.Action("LoaiTaiKhoan")">Loại tài khoản</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<!-- [ table ] start -->
<div class="col-xl-12">
    <div class="card">
        <div class="card-header">
            <h5>Loại tài khoản</h5>
        </div>
        <div class="card-block table-border-style">
            <div style="text-align:right;">
                <a asp-controller="TaiKhoan" asp-action="ThemLoaiTaiKhoan" class="btn btn-primary feather icon-plus" style="text-align:right;">     Thêm</a>
            </div>
            <div class="table-responsive">
                <table class="table table-striped content-table colortoptable">
                    <thead>
                        <tr>
                            <th>Mã loại</th>
                            <th>Tên nhóm tài khoản</th>
                            <th>Chức năng</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@Html.DisplayFor(m => item._sMaLoai)</td>
                                <td>@Html.DisplayFor(m => item._sTenLoai)</td>
                                <td>
                                    <a href="@Url.Action("SuaLoaiTaiKhoan", "TaiKhoan", new { id = item._sMaLoai})" class="btn btn-success feather icon-edit"></a>
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
                <!--Phan trang-->
                <nav aria-label="Page navigation example">
                    @if (pager.TotalPages > 0)
                    {
                        <ul class="pagination">
                            @if (pager.CurrentPage > 1)
                            {
                                <li class="page-item">
                                    <a class="page-link" href="@Url.Action("TaiKhoan", "LoaiTaiKhoan", new {page =1})">Frist</a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link" href="@Url.Action("TaiKhoan", "LoaiTaiKhoan", new {page =pager.CurrentPage - 1})">Previous</a>
                                </li>
                            }

                            @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
                            {
                                <li class="page-item @(pge == pager.CurrentPage ? "active":"")">
                                    <a class="page-link" href="@Url.Action("TaiKhoan", "LoaiTaiKhoan", new { page = @pge})">@pge</a>
                                </li>

                            }

                            @if (pager.CurrentPage < pager.TotalPages)
                            {
                                <li class="page-item">
                                    <a class="page-link" href="@Url.Action("TaiKhoan", "LoaiTaiKhoan", new {page = pager.CurrentPage + 1 })">Next</a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link" href="@Url.Action("TaiKhoan", "LoaiTaiKhoan", new {page = pager.TotalPages })">Last</a>
                                </li>
                            }
                        </ul>
                    }
                </nav>
            </div>
        </div>
    </div>
</div>
<!-- [ table ] end -->

Views/TaiKhoan/SuaLoaiTaiKhoan.cshtml
@model QuanLyVienPhi.Models.AccountGroup;
@{
    ViewData["Title"] = "Sửa loại tài khoản";
    if (ViewBag.Session == "Ad".ToLower().Trim())
    {
        Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    }

}

<div class="page-header">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-12">
                <div class="page-header-title">

                </div>
                <ul class="breadcrumb">
                    @*<li class="breadcrumb-item"><a href="@Url.Action("KeToan")"><i class="feather icon-home"></i></a></li>*@
                    <li class="breadcrumb-item"><a href="@Url.Action("LoaiTaiKhoan")">Loại tài khoản</a></li>
                    <li class="breadcrumb-item"><a href="@Url.Action("SuaLoaiTaiKhoan")">Sửa loại tài khoản</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="col-sm-12">
    <div class="card">
        <div class="card-header">
            <h5>Sửa loại tài khoản</h5>
        </div>
        <div class="card-body">
            <h5>Tài khoản</h5>
            <hr>
            <div class="row">
                <div class="col-md-6">
                    @using (Html.BeginForm("SuaLoaiTaiKhoan", "TaiKhoan", FormMethod.Post))
                    {
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="_sMaLoai" class="control-label">Mã loại</label>
                            <input name="_sMaLoai" asp-for="_sMaLoai" class="form-control" />
                            <span asp-validation-for="_sMaLoai" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="_sTenLoai" class="control-label">Tên loại</label>
                            <input asp-for="_sTenLoai" class="form-control" name="_sTenLoai" />
                            <span asp-validation-for="_sTenLoai" class="text-danger"></span>
                        </div>
                        <input type="submit" value="Lưu" class="btn btn-primary" />
                        <a asp-controller="TaiKhoan" asp-action="LoaiTaiKhoan" class="btn btn-outline-secondary feather icon-corner-down-right">     Trở về</a>
                    }
                </div>
                <div class="col-md-6">
                    <form>
                        <div class="form-group">
                            <img src="~/Images/medical-12_icon-icons.com_73944.png" alt="" style="width:50%; margin-left:130px;" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Views/TaiKhoan/SuaTaiKhoan.cshtml
@model QuanLyVienPhi.Models.Account
@{
    ViewData["Title"] = "Sửa tài khoản";
    if (ViewBag.Session == "Ad".ToLower().Trim())
    {
        Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    }
}

<div class="page-header">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-12">
                <div class="page-header-title">

                </div>
                <ul class="breadcrumb">
                    @*<li class="breadcrumb-item"><a href="@Url.Action("KeToan")"><i class="feather icon-home"></i></a></li>*@
                    <li class="breadcrumb-item"><a href="@Url.Action("DSTaiKhoan")">Danh sách tài khoản</a></li>
                    <li class="breadcrumb-item"><a href="@Url.Action("SuaTaiKhoan")">Sửa tài khoản</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="col-sm-12">
    <div class="card">
        <div class="card-header">
            <h5>Sửa tài khoản</h5>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    @using (Html.BeginForm("SuaTaiKhoan", "TaiKhoan", FormMethod.Post))
                    {
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="_sTaiKhoan" class="control-label">Tài khoản</label>
                            <input asp-for="_sTaiKhoan" class="form-control" name="_sTaiKhoan" />
                            <span asp-validation-for="_sTaiKhoan" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="_sMatKhau" class="control-label">Mật khẩu</label>
                            <input type="password" asp-for="_sMatKhau" class="form-control" name="_sMatKhau" />
                            <span asp-validation-for="_sMatKhau" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="_sMaLoai">Quyền</label>
                            <input asp-for="_sMaLoai" class="form-control" name="_sMaLoai" />
                            <span asp-validation-for="_sMaLoai" class="text-danger"></span>
                            @*<select class="form-control" id="exampleFormControlSelect1" name="_sMaLoai"
                                asp-items="@(new SelectList(ViewBag.InfoAccGr,"Value","Text"))"></select>*@
                        </div>
                        <div class="form-group">
                            <label asp-for="_sMANV">Nhân viên</label>
                            <input asp-for="_sMANV" class="form-control" name="_sMANV" />
                            <span asp-validation-for="_sMANV" class="text-danger"></span>
                            @*<label for="exampleFormControlSelect1">Nhân viên</label>
                                <select class="form-control" id="exampleFormControlSelect1" name="_sMANV"
                                        asp-items="@(new SelectList(ViewBag.InfoEmp,"Value","Text"))"></select>*@
                        </div>

                        <input type="submit" value="Lưu" class="btn btn-primary feather icon-save" />
                        <a asp-controller="TaiKhoan" asp-action="DSTaiKhoan"
                           class="btn btn-outline-secondary feather icon-corner-down-right">     Trở về</a>

                    }
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <img src="~/Images/test_102328.png" alt="" style="width:50%; margin-left:130px;" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/TaiKhoan/ThemLoaiTaiKhoan.cshtml
@{
    ViewData["Title"] = "Thêm loại tài khoản";
    if (ViewBag.Session == "Ad".ToLower().Trim())
    {
        Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    }
}

<div class="page-header">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-12">
                <div class="page-header-title">

                </div>
                <ul class="breadcrumb">
                    @*<li class="breadcrumb-item"><a href="@Url.Action("KeToan")"><i class="feather icon-home"></i></a></li>*@
                    <li class="breadcrumb-item"><a href="@Url.Action("LoaiTaiKhoan")">Loại tài khoản</a></li>
                    <li class="breadcrumb-item"><a href="@Url.Action("ThemLoaiTaiKhoan")">Thêm loại tài khoản</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="col-sm-12">
    <div class="card">
        <div class="card-header">
            <h5>Thêm loại tài khoản</h5>
        </div>
        <div class="card-body">
            <h5>Tài khoản</h5>
            <hr>
            <div class="row">
                <div class="col-md-6">
                    @using (Html.BeginForm("ThemLoaiTaiKhoan", "TaiKhoan", FormMethod.Post))
                    {
                        <div class="form-group">
                            <label>Mã loại</label>
                            <input type="text" class="form-control" name="_sMaLoai">
                        </div>
                        <div class="form-group">
                            <label>Tên loại</label>
                            <input type="text" class="form-control" name="_sTenLoai">
                        </div>
                        <input type="submit" value="Lưu" class="btn btn-primary feather icon-save">
                        <a asp-controller="TaiKhoan" asp-action="LoaiTaiKhoan" class="btn btn-outline-secondary feather icon-corner-down-right">     Trở về</a>
                    }
                </div>
                <div class="col-md-6">
                    <form>
                        <div class="form-group">
                            <img src="~/Images/medical-12_icon-icons.com_73944.png" alt="" style="width:50%; margin-left:130px;" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Views/TaiKhoan/ThemTaiKhoan.cshtml
@{
    ViewData["Title"] = "Thêm tài khoản";
    if (ViewBag.Session == "Ad".ToLower().Trim())
    {
        Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    }
}

<div class="page-header">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-12">
                <div class="page-header-title">

                </div>
                <ul class="breadcrumb">
                    @*<li class="breadcrumb-item"><a href="@Url.Action("KeToan")"><i class="feather icon-home"></i></a></li>*@
                    <li class="breadcrumb-item"><a href="@Url.Action("DSTaiKhoan")">Danh sách tài khoản</a></li>
                    <li class="breadcrumb-item"><a href="@Url.Action("ThemTaiKhoan")">thêm tài khoản</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="col-sm-12">
    <div class="card">
        <div class="card-header">
            <h5>Thêm tài khoản</h5>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    @using (Html.BeginForm("ThemTaiKhoan", "TaiKhoan", FormMethod.Post))
                    {
                        <div class="form-group">
                            <label>Tên đăng nhập</label>
                            <input type="text" class="form-control" name="_sTaiKhoan">
                        </div>
                        <div class="form-group">
                            <label>Mật khẩu</label>
                            <input type="password" class="form-control" name="_sMatKhau">
                        </div>
                        <div class="form-group">
                            <label for="exampleFormControlSelect1">Quyền</label>
                            <select class="form-control" id="exampleFormControlSelect1" name="_sMaLoai"
                                    asp-items="@(new SelectList(ViewBag.InfoAccGr,"Value","Text"))"></select>
                        </div>
                        <div class="form-group">
                            <label for="exampleFormControlSelect1">Nhân viên</label>
                            <select class="form-control" id="exampleFormControlSelect1" name="_sMANV"
                                    asp-items="@(new SelectList(ViewBag.InfoEmp,"Value","Text"))"></select>
                        </div>
                        <input type="submit" value="Lưu" class="btn btn-primary feather icon-save">
                        <a asp-controller="TaiKhoan" asp-action="DSTaiKhoan" class="btn btn-outline-secondary feather icon-corner-down-right">     Trở về</a>
                    }
                </div>
                <div class="col-md-6">
                    <form>
                        <div class="form-group">
                            <img src="~/Images/test_102328.png" alt="" style="width:50%; margin-left:130px;" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>